# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  repository_dispatch:
    types: [tohl_upload]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Download Export File
        uses: carlosperate/download-file-action@v1.0.3
        id: download-poetry
        with:
            file-url: ${{ secrets.TOHL_FILE_URL }}
            file-name: 'tohl_data.zip'
            location: './upload'
      - name: Decompress
        uses: TonyBogdanov/zip@1.0
        with:
          args: unzip -qq ${{ steps.download-poetry.outputs.file-path }} -d ./import-data
      - name: Install dependencies
        run: npm i

      - name: Generate
        run: node index.js

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./api
